services:
  wmsettings.settings:
    class: Drupal\wmsettings\Service\WmSettings
    arguments: ['@entity.manager', '@entity_type.manager', '@entity.query', '@language_manager', '@config.factory', '@entity.repository']
